# Cloud Run deployment configuration for CareerLens
# Deploy API service to Cloud Run
# Usage: gcloud run deploy careerlens-api --source=. --region=us-central1

apiVersion: v1
kind: CloudRunService
metadata:
  name: careerlens-api
  namespace: careerlens
spec:
  template:
    spec:
      containers:
        - name: api
          image: gcr.io/careerlens-project/careerlens-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: careerlens-secrets
                  key: database-url
            - name: ALEMBIC_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: careerlens-secrets
                  key: alembic-database-url
            - name: CORS_ORIGINS
              value: "https://careerlens-web.run.app"
            - name: PINECONE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: careerlens-secrets
                  key: pinecone-api-key
            - name: PINECONE_INDEX_NAME
              value: "careerlens"
            - name: PINECONE_NAMESPACE
              value: "recommendations"
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              cpu: "0.5"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "1Gi"
      timeout: 3600s
  traffic:
    - percent: 100
      latestRevision: true
  autoscaling:
    minInstances: 1
    maxInstances: 10

---
apiVersion: v1
kind: CloudRunService
metadata:
  name: careerlens-web
  namespace: careerlens
spec:
  template:
    spec:
      containers:
        - name: web
          image: gcr.io/careerlens-project/careerlens-web:latest
          ports:
            - containerPort: 3000
          env:
            - name: VITE_API_BASE_URL
              value: "https://careerlens-api.run.app/api/v1"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              cpu: "0.25"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
      timeout: 3600s
  traffic:
    - percent: 100
      latestRevision: true
  autoscaling:
    minInstances: 1
    maxInstances: 5

---
apiVersion: v1
kind: Secret
metadata:
  name: careerlens-secrets
  namespace: careerlens
type: Opaque
stringData:
  database-url: "postgresql://user:pass@cloudsql-instance/careerlens"
  alembic-database-url: "postgresql://user:pass@cloudsql-instance/careerlens"
  pinecone-api-key: ""
